---
title: "Practico_2"
author: "Norris-Carranza"
date: "5/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Clustering absenteeism at work

## Load Libraries

```{r}
# Load libraries
#library(corrplot)
library(class)
library(gmodels)
```

## Load data

```{r echo=TRUE}
# Seeds
# https://archive.ics.uci.edu/ml/datasets/seeds
# The dataset was a plain .txt file, was transformed into .csv following the description provided
# The seeds being classified are: Kama, Rosa and Canadian. 70 elements each, randomly selected for # the experiment 
original <- read.csv(file="../datasets/seeds.csv", header=TRUE, sep=",")
# Shuffle the data (the original is ordered by seed type)
dataset <- original[sample(nrow(original)),]
```

### View a couple of rows

```{r}
head(dataset)
```

# View summary
```{r}
summary(dataset)
```

# View summary
```{r}
dataset$seed_type
```

# Normalize data
```{r}
# Drop 'seed_type' column
data_to_norm <- dataset[, 1:7]

# Apply z-score normalization to the data
normalized_dataset <- as.data.frame(scale(data_to_norm))

# For training we are going to take 80% of the data and for testing the remaining 20%
# Create train and test indexes
nr_rows <- nrow(normalized_dataset)
partition_index = ceiling(nr_rows*0.8)
train_indexes = 1:partition_index
test_indexes = (partition_index + 1):nr_rows

# Pick the labels for the test and train sets
data_train_labels <- dataset[train_indexes, 'seed_type']
data_test_labels  <- dataset[test_indexes, 'seed_type']
table(data_train_labels)
table(data_test_labels)


data_train <- normalized_dataset[train_indexes,]
data_test  <- normalized_dataset[test_indexes,]

data_test_pred <- knn(train=data_train, test=data_test, cl=data_train_labels, k=2)
CrossTable(x=data_test_labels , y=data_test_pred, prop.chisq = FALSE)
```

